### PR TITLE
issue-56: fix binary serialization compatibility problem with time_duration

### LINKED ISSUE #56: posix_time's no longer boost::serialize between boost v1.64 and v1.65, 1.66
It appears that 

[4543: fix ptime 2038 issue ](https://github.com/boostorg/date_time/commit/818dea52f3f0c8b4f5172df13c5fa4f57340625f#diff-c68588b074fe6450f9ed1dedc759621e)

has changed the behavior of boost::serialization.  My archives (built with boost 1.64) using boost::serialization (inherently using time_serialization.hpp) no longer load because the hours, minutes, etc fields are now 8 bytes instead of 4 bytes.

I'm using VS2017 15.4 and 15.2

### PR DESCRIPTION
**Pull request by jeking3**
This fixes #56

### CODE REVIEW

File: include/boost/date_time/time_resolution_traits.hpp [hunk 1]
```diff
@@ -68,7 +68,7 @@ namespace date_time {
            typename frac_sec_type::int_type resolution_adjust,
 #endif
            unsigned short frac_digits,
-           typename var_type = std::time_t >
```
Comment (eldiener) [inline include/boost/date_time/time_resolution_traits.hpp]: The type var_type defaults to a value, but that can be overridden. Does this affect the serialization code which you have corrected ? In other words can the end-user change the time_duration internal types by configuration time_resolution_traits differently ? If so, in that case isn't the correct code always to use the time_resolution_traits var_type as the type used to serialize rather than doing asserts to make sure the type is always the var_type default ?

Comment (jeking3) [reply include/boost/date_time/time_resolution_traits.hpp]: So if we had the static assertions in the code before this, and they all used var_type, they would all have passed when var_type changed.  This would have defeated the purpose of the static asserts, which is to protect the binary format compatibility.  In Boost 1.65.1 and earlier var_type was `boost::int32_t` which had the year 2038 problem.  In 1.66.0 the var_type changed to `std::time_t`, thus causing it to vary on different platforms.  By changing it to boost::int64_t and ensuring the output size is 64-bits with static assertions, it protects the binary serialization.

Comment (mclow) [reply include/boost/date_time/time_resolution_traits.hpp]: You should put that comment "_In Boost 1.65.1 and earlier var_type was boost::int32_t which had the year 2038 problem. In 1.66.0 the var_type changed to std::time_t, thus causing it to vary on different platforms. By changing it to boost::int64_t and ensuring the output size is 64-bits with static assertions, it protects the binary serialization._" in the source code, so that people will know why it is this way.

Comment (jeking3) [reply include/boost/date_time/time_resolution_traits.hpp]: Okay, will do and push later.

Comment (eldiener) [reply include/boost/date_time/time_resolution_traits.hpp]: Can the var_type be changed by the end-user ? Or is time_resolution_traits strictly used internally ? if the latter I have no objection to the serialization code in this fix. But if time_resolution_traits, and therefore var_type, can be used by the end-user to change the time duration types then I think the serialization code must use the var_type rather than assume a hardcoded setting which is merely the default type for the var_type.

Comment (jeking3) [reply include/boost/date_time/time_resolution_traits.hpp]: I believe posix_time_config.hpp is the only consumer, and it relies on the default value.
